### ISSUE TITLE
Add cookieplone version and cookieplone-template revision (not available yet) to all the generated README´s

### ISSUE THREAD

**Issue by acsr** [plone/cookieplone-templates#143]
The project resulting from the project template misses an obvious possibility to check traces from what versions the deployments derives.

- It would also help to add a changelog if and how you update a project setup (Makefiles etc.) after serious changes.
- To go further every written logic (e.g. Makefiles) should contain proper version strings from creation.
- This would really help during diffs and debugging when something changes in the gearbox.
- These versions should be also displayed in the summary after the run of cookieplone beyond the versions of the underlying prerequisites like Node etc. 
- Sanity check results: did not report the found versions and limitations/constraints:

│   - Cookieplone: ✓
│   - Python: ✓
│   - Node: ✓
│   - git: ✓
│   - Docker (optional): ✓

You could leave that to an expert/debug mode, but why?

**Comment by davisagli** [comment]
@acsr The readmes already include a notice like this:

> ## Credits and Acknowledgements 🙏

> Crafted with care by **Generated using [Cookieplone (0.8.2)](https://github.com/plone/cookieplone) and [cookiecutter-plone (2638336)](https://github.com/plone/cookiecutter-plone/commit/2638336ff1127c169063964cd95251292c954a0b) on 2025-02-02 20:55:34.561372**. A special thanks to all contributors and supporters!

I see it has some small errors that need to be fixed:
- bad grammar "Crafted with care by Generated using..."
- It uses the old repository URL plone/cookiecutter-plone instead of plone/cookieplone-templates

But this is basically what you asked for, right?

**Comment by acsr** [comment]
Why the hell did I missed it? Maybe I am stuck in the deeper readme.md that definitely miss this information.
I checked it now only in the unrendered Markdown and it was buried in the Textwall of the file in the Root.

Nevertheless the other locations I mentioned are worth considering to dump that notice there as well.

The Headline "## Credits and Acknowledgements 🙏" does the rest to make you version blind.
The whole notice and a proper headline should be rendered in the early stage of the cookieplone run into a variable.

@davisagli Thanks for the answer.

**Comment by davisagli** [comment]
I fixed the small problems I mentioned in https://github.com/plone/cookieplone/pull/65 and https://github.com/plone/cookieplone-templates/pull/144

**Comment by acsr** [comment]
@davisagli Actually your changes did not fix the issue. You changed the templates, but today we figured out that the actual code generating the __generator-signature is not in the cookiecutter.json but in the `__generator-signature` function located in Cookieplone itself at /utils/settings.py

The current message still mentions the `Cookiecutter` version an the `cookiecutter-plone` version and is not using your template wording at all.

**Comment by davisagli** [comment]
@acsr I know the `__generator_signature` definitions in cookieplone-templates are not used. That's why I also did the fix in https://github.com/plone/cookieplone/pull/65, which is not released yet.
